name: Call Reusable Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  using_image_resize_and_release:
    name: Calling GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
     - name: call-workflow
       uses: actions/checkout@v4

