name: Call Reusable Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  new-release:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
  call-workflow:
    uses: mcsully323/DigitalTrailsTest/.github/workflows/release_creation.yml@main  
